rabbitConfig:
  host: "122.51.241.101"
  port: "5672"
  userName: "admin"
  password: "qhlk@2017"
  virtualHost: "/"
  radarQueueName: "itsu.radar.queue"
  radarQueueExchange: "itsu.radar.exchange"
  radarQueueRoutingKey: "radar"